/**
 * A utility function to fetch data from a mock API and enrich it with descriptions
 * generated by a local Ollama instance.
 *
 * @returns {Array<Object>} An array of enriched data asset objects.
 * @throws {Error} Throws an error if the mock API or Ollama API calls fail.
 */
export const fetchAndEnrichAssets = async () => {
  try {
    // 1. Fetch data from the mock API
    const response = await fetch('http://localhost:3333/api/assets');
    if (!response.ok) {
      throw new Error('Failed to fetch data from mock API');
    }
    const apiAssets = await response.json();

    // 2. Enrich each asset with a description from the Ollama API
    const updatedAssets = await Promise.all(
      apiAssets.map(async (asset) => {
        // Construct a specific prompt for the Ollama model
        const prompt = `Provide a detailed and professional description for a data asset named "${asset.name}" which is a "${asset.type}" and comes from a "${asset.source}" source. Do not use quotes in the response. Keep it concise, about 2-3 sentences.`;

        // The Ollama API endpoint
        const apiUrl = 'http://localhost:11434/api/generate';

        // The payload structure for the Ollama API is different from Gemini's
        const ollamaPayload = {
          model: 'gemma2:2b', // You can change this to any model you have downloaded
          prompt: prompt,
          stream: false // We need the full response at once
        };
        
        try {
          // Make the Ollama API call
          const ollamaResponse = await fetch(apiUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(ollamaPayload)
          });
          // console.log("Received", ollamaResponse.headers.get('content-length'), " bytes")
          const result = await ollamaResponse.json();
          
          // Ollama's response format is simpler. The generated text is in the 'response' field.
          const description = result?.response || 'No description available.';
          return { ...asset, description };
        } catch (error) {
          console.error('Error fetching description from Ollama API:', error);
          // Return a fallback description in case of an error
          return { ...asset, description: `A data asset from ${asset.source} containing important business data.` };
        }
      })
    );
    // Return the final array of enriched assets
    return updatedAssets;
  } catch (err) {
    console.error('Error in fetching and enriching data:', err);
    throw err; // Re-throw the error to be handled by the caller
  }
};

/**
 * Creates a new data asset by sending a POST request to the backend.
 * * @param {Object} asset The new asset data to create.
 * @returns {Promise<Object>} The newly created asset object from the backend.
 */
export const createAsset = async (asset) => {
  try {
    const response = await fetch('http://localhost:3333/api/assets', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(asset),
    });

    if (!response.ok) {
      throw new Error(`Failed to create asset: ${response.statusText}`);
    }

    return response.json();
  } catch (error) {
    console.error('Error creating asset:', error);
    throw error;
  }
};

/**
 * Updates an existing data asset by sending a PUT request to the backend.
 * * @param {Object} asset The updated asset data.
 * @returns {Promise<Object>} The updated asset object from the backend.
 */
export const updateAsset = async (asset) => {
  try {
    const response = await fetch(`http://localhost:3333/api/assets/${asset.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(asset),
    });

    if (!response.ok) {
      throw new Error(`Failed to update asset: ${response.statusText}`);
    }

    return response.json();
  } catch (error) {
    console.error('Error updating asset:', error);
    throw error;
  }
};

/**
 * Deletes a data asset by sending a DELETE request to the backend.
 * * @param {string} assetId The ID of the asset to delete.
 * @returns {Promise<void>} A promise that resolves if the deletion is successful.
 */
export const deleteAsset = async (assetId) => {
  try {
    const response = await fetch(`http://localhost:3333/api/assets/${assetId}`, {
      method: 'DELETE',
    });

    if (!response.ok) {
      throw new Error(`Failed to delete asset: ${response.statusText}`);
    }
  } catch (error) {
    console.error('Error deleting asset:', error);
    throw error;
  }
};
